name: lab_7_415904_test

on:
  push:
    branches:
      - lab_7/415904
    
jobs:
  test_dodawanie:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    
    - name: prepare environemnt 
      run: |
         cd env_415904 && python -m pip install -r requirements.txt
      

    - name: Run test
      run: |
          cd env_415904 && pytest calculator_test.py::test_dodawanie

  test_odejmowanie:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    
    - name: prepare environemnt 
      run: |
         cd env_415904 && python -m pip install -r requirements.txt
      

    - name: Run test
      run: |
          cd env_415904 && pytest calculator_test.py::test_odejmowanie

  test_mnozenie:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    
    - name: prepare environemnt 
      run: |
         cd env_415904 && python -m pip install -r requirements.txt
      

    - name: Run test
      run: |
          cd env_415904 && pytest calculator_test.py::test_mnozenie
  test_dzielenie:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    
    - name: prepare environemnt 
      run: |
         cd env_415904 && python -m pip install -r requirements.txt
      

    - name: Run test
      run: |
          cd env_415904 && pytest calculator_test.py::test_dzielenie
          
  test_pandas:
    needs: [test_dodawanie,test_mnozenie,test_odejmowanie,test_dzielenie]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    
    - name: prepare environemnt 
      run: |
         cd env_415904 && python -m pip install -r requirements.txt
      

    - name: Run test
      run: |
          cd env_415904 && pytest numpy_tests.py

